### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/bodega-solution#9]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Reflection

- [x] No TODO markers left in reflection.md
- [ ] reflection.md contains a list
- [ ] reflection.md contains at least 300 words
- [ ] reflection.md answers all questions

## Static Site Servicing

- [ ] No TODO markers left in _config.yml
- [ ] No TODO markers left in about.md

## Stockroom Stocking

- [ ] Example list file removed from stockroom
- [ ] Example department removed from stockroom
- [x] Each department contains at least 10 items

## Percent complete

Based on the checks achieved, this assignment is `22%` complete.
